### ISSUE TITLE
Logo Design For Relisten Android

### ISSUE THREAD

**Issue by zularizal** [swbain/relisten-android#1]
Hi @swbain , I'm a graphic designer. I am interested and like your project. I want to contribute by designing a logo for your project.
Can I contribute?

**Comment by swbain** [comment]
Hey @zularizal! I'm probably not the best person to ask, as this is just an Android implementation of a larger project (relisten.net). If you want to contribute, I'd recommend joining the discord server and introducing yourself in the #new-contributors channel! Here's an invite link: https://discordapp.com/invite/73fdDSS
